CREATE DATABASE sistema;

CREATE TABLE public.contactos
(
    idcontacto integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombrecontacto character varying(40) COLLATE pg_catalog."default",
    apellidocontacto character varying(60) COLLATE pg_catalog."default",
    numcontacto character varying COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.contactos
    OWNER to postgres;


INSERT INTO public.contactos (nombrecontacto, apellidocontacto,numcontacto)
VALUES('Deury', 'Ferreira', '829-327-0889');

INSERT INTO public.contactos (nombrecontacto, apellidocontacto,numcontacto)
VALUES('Rocio', 'Ferreira', '829-478-1119');

INSERT INTO public.contactos (nombrecontacto, apellidocontacto,numcontacto)
VALUES('Pedro Luis', 'Lopez', '1-800-388-1820');

